# Generated by Django 2.0.1 on 2018-02-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_des', '0002_auto_20180212_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='is_occupied',
            field=models.BooleanField(default=True),
        ),
    ]
